### ISSUE TITLE
Ложные срабатывания на VirusTotal

### ISSUE THREAD

**Issue by username1565** [AHOHNMYC/uAnon#1]
Just uploaded uAnon.exe to virustotal and see this:
https://www.virustotal.com/gui/file/10c858ff5d1fa226188ae610ef79d8bc5c288da6470a72b884b77fc5245dc5ff/detection

Удолил тебя дважды, в токсе - за это.

**Comment by AHOHNMYC** [comment]
# Чё?

### Про ложные срабатываня (false positive) не слышал?
Там код даже не пожат. Всё лежит в открытом виде — бери и читай в HIEW/IDA/x64dbg.
Нет, хочу жрать говно и верить антивирусам на слово.

### Сукаблять, это **опенсорцный проект**.
Знаешь, что это значит? Сюрприз-сюрприз! Ты можешь просто взять, сходить на сайт [flat assembler](https://flatassembler.net), скачать оттуда [fresh](https://fresh.flatassembler.net) и **сам** собрать себе проигрыватель. Если он тебе, конечно, зачем-то вообще понадобился.

### Более того, это не просто опенсорцный проект. Это **мой** опенсорцный проект.
Не нравится что-то? Форкай и переписывай как душе угодно.

**Comment by AHOHNMYC** [comment]
Прошу прощения у наблюдателей. Это внутренний конфликт.
Ко всем остальным действует презумпция ума и доброжелательности :cat:

**Comment by AHOHNMYC** [comment]
После отправки писем с жалобой на неверные алгоритмы работы антивирусов, адекватно отреагировала только Microsoft. От остальных мелких софтоклепаторов пришли ответы уровня "это вирус" и "жалобы на false positive доступны только нашим клиентам. Купите наш антивирус".

Отдельно порадовала компания TrendMicro. Ни один из e-mail адресов, предоставленных поддержкой VirusTotal, не является действующим. Вместо ответов с извинениями, приходят отписки от почтового демона.

![Безымянный](https://user-images.githubusercontent.com/24810600/64206035-1131a200-cea2-11e9-9b93-1195494d3294.png)
![Безымянный1](https://user-images.githubusercontent.com/24810600/64206037-11ca3880-cea2-11e9-8163-2e966ed15c81.png)

Что характерно, ни один из зарекомендовавших себя на рынке продуктов (AVG, Avira, Kaspersky, и что удивительно, Eset Nod32) не сочли файл ни опасным, ни подозрительным. Хотя думал, что изначально расклад будет прямо противоположным.

В завершение могу только сослаться на опыт коллег: [Nir Sofeir](http://blog.nirsoft.net/2009/05/17/antivirus-companies-cause-a-big-headache-to-small-developers/), [CoolSoft](https://coolsoft.altervista.org/en/blog/2018/05/antivirus-false-positives-are-plague-small-developers), 
И дать ссыли ещё на пару анализаторов поведения: [Jotti](https://virusscan.jotti.org/ru-RU/filescanjob/accpso1yyj), [Hybrid analysis](https://www.hybrid-analysis.com/sample/10c858ff5d1fa226188ae610ef79d8bc5c288da6470a72b884b77fc5245dc5ff). Последний результат особенно забавен: это всё делаю не я, а встроенный в винду же DirectShow.

Больше даже пытаться бороться с ветряными мельницами не буду, хех.

**Comment by AHOHNMYC** [comment]
Внезапно **Sophos ML** — единственный продукт, авторам которого я даже не пробовал писать, — изменил эвристические алгоритмы.
Чудеса. И, конечно, никакой связи с MS, ну что вы.

Продолжаю зоонаблюдать.
![](https://user-images.githubusercontent.com/24810600/64308509-2ee63080-cfa2-11e9-8980-3ec43ef6a760.png)

**Comment by username1565** [comment]
Там 37 строк всего, в `.asm` файле, с этого и ржу.

**Comment by username1565** [comment]
@AHOHNMYC, там 37 строк всего, в том `.asm` файле, с этого и ржу.

У меня, на Windows XP, проигрыватель - не работает.
В фаерволе, я вижу, что открывается три исходящих соединения,
а затем они закрываются и всё. Окно висит...
Тем не менее, ссылка из исходника: https://anon.fm/streams/radio
позволяет безо всякого проигрывателя -
слушать радио-поток в `Firefox ESR 52.9.0 (32-бит)`,
а также в `Google Chrome 34.0.1847.131 m` и в `Chromium 54.20.6530.0`,
прямо в браузерах - встроенными в них проигрывателями.

Добавил в закладки.

**Comment by AHOHNMYC** [comment]
Работа/не работа в разных средах — другой объект рассмотрения, никак не связанный с антивирусами.
